language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - python setup.py flake8
  - python setup.py test

notifications:
  email:
    - tomaz+travis@tomaz.me
